### ISSUE TITLE
TypeScript error when importing chessbored: "Type 'Event' is not generic."

### ISSUE THREAD

**Issue by jpulgarin** [espenh/chessbored#1]
When imporing `chessbored` into my TypeScript project I get the following error:

```
[~/dev/repertoire/repertoire/static/js]$ tsc test.ts 
../../../node_modules/chessbored/lib/chessboard.d.ts:13:38 - error TS2315: Type 'Event' is not generic.

13     throttledMousemoveWindow: ((evt: JQuery.Event<EventTarget, null>) => void) & _.Cancelable;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../../node_modules/chessbored/lib/chessboard.d.ts:14:38 - error TS2315: Type 'Event' is not generic.

14     throttledTouchmoveWindow: ((evt: JQuery.Event<EventTarget, null>) => void) & _.Cancelable;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

All `test.ts` does is import `chessbored`. I've tried importing in all the following ways:

```
import * as ChessBoard from 'chessbored';
import { ChessBoard} from 'chessbored';
import chessbored = require('chessbored');
```

I've also tried import `jQuery` above the `chessbored` import.

Lastly, this is my `tsconfig.json`:

```
{
  "compilerOptions": {
    "sourceMap": true,
    "strict": true,
    "alwaysStrict": true,
    "strictNullChecks": false,
    "noImplicitAny": false
  },
  "include": ["**/*.ts"],
  "exclude": ["node_modules"]
}
```

I'm very new to TypeScript so I assume this is a mistake on my end and not yours.

**Comment by espenh** [comment]
Hey, thanks for the heads up! This was an issue with the types used to handle touch and mouse events. Update to the latest chessbored version (0.0.3), and that should fix your issue. Let me know if it doesn't.

Your code should be alright. The website project in this repository has a basic usage example here: https://github.com/espenh/chessbored/blob/master/packages/website/src/boardContainer.tsx#L2.

**Comment by jpulgarin** [comment]
Thanks @espenh !
